name: Build aapt2

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'     
        required: false
        default: 'Update package'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_arch: [x86_64, x86, arm64-v8a, armeabi-v7a]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23c
          add-to-path: false
      - run: ./build.sh ${{ matrix.target_arch }}
        env:
          NDK_TOOLCHAIN: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.target_arch }}
          path: dist

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
      - run: |
          mkdir dist
          for arch in x86_64 x86 arm64-v8a armeabi-v7a; do
            mv dist-$arch/$arch/aapt2 dist/aapt2-$arch
          done
      - run: echo "date=$(date --utc +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      - uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*
          tag: ${{ env.date }}
